// 案例页唯一配置入口。
// 新增作品时，复制下面的对象模板到 caseVideos 数组中并填写内容即可。
// 视频和封面既可以使用云端地址，也可以放在 public/videos 与 public/covers 目录中。
//
// {
//   id: "唯一编号",
//   title: "作品标题",
//   category: "作品类型",
//   summary: "作品简介",
//   videoSrc: "视频地址",
//   posterSrc: "封面地址",
//   duration: "时长",
//   orientation: "横屏或竖屏",
// },

const publicBase = import.meta.env.BASE_URL;

export const caseVideos = [
  {
    id: "soul-guide",
    title: "渡魂使者",
    category: "3D动漫",
    summary: "三维动漫叙事样片，呈现暗黑奇幻氛围与电影化镜头语言。",
    videoSrc: `${publicBase}videos/soul-guide.mp4`,
    posterSrc: `${publicBase}covers/soul-guide.jpg`,
    duration: "01:24",
    orientation: "横屏",
  },
  {
    id: "judge",
    title: "判官",
    category: "3D动漫",
    summary: "三维动漫奇幻短剧样片，展示现代与冥界交错、角色动作与电影化场景。",
    videoSrc: `${publicBase}videos/judge.mp4`,
    posterSrc: `${publicBase}covers/judge.jpg`,
    duration: "01:27",
    orientation: "横屏",
  },
  {
    id: "two-dimensional-anime",
    title: "二维动漫",
    category: "2D动漫",
    summary: "二维动漫叙事样片，展示风格化角色、生活化表演与连续画面。",
    videoSrc: `${publicBase}videos/2d-anime.mp4`,
    posterSrc: `${publicBase}covers/2d-anime.jpg`,
    duration: "01:16",
    orientation: "横屏",
  },
  {
    id: "redstone-village",
    title: "怒江红石村",
    category: "仿真人",
    summary: "仿真人现实题材样片，展示人物情绪、写实环境与竖屏叙事。",
    videoSrc: `${publicBase}videos/redstone-village.mp4`,
    posterSrc: `${publicBase}covers/redstone-village.jpg`,
    duration: "01:48",
    orientation: "竖屏",
  },
  {
    id: "ragnarok-trailer",
    title: "诸神黄昏预告",
    category: "仿真人",
    summary: "仿真人奇幻预告样片，展示神话世界、角色对峙与电影化视效。",
    videoSrc: `${publicBase}videos/ragnarok-trailer.mp4`,
    posterSrc: `${publicBase}covers/ragnarok-trailer.jpg`,
    duration: "01:01",
    orientation: "竖屏",
  },
  {
    id: "flash-marriage",
    title: "闪婚",
    category: "仿真人",
    summary: "仿真人都市情感样片，展示角色一致性、表演细节与短剧节奏。",
    videoSrc: `${publicBase}videos/flash-marriage.mp4`,
    posterSrc: `${publicBase}covers/flash-marriage.jpg`,
    duration: "01:03",
    orientation: "竖屏",
  },
  {
    id: "hospital-chaos",
    title: "医院闹翻天",
    category: "仿真人",
    summary: "仿真人喜剧短剧样片，展示医院群像、轻喜节奏与生活化表演。",
    videoSrc: `${publicBase}videos/hospital-chaos.mp4`,
    posterSrc: `${publicBase}covers/hospital-chaos.jpg`,
    duration: "01:16",
    orientation: "竖屏",
  },
  {
    id: "chosen-by-billionaire",
    title: "被当作小偷赶走，却被亿万富翁选中",
    category: "仿真人",
    summary: "仿真人海外短剧样片，展示身份反转、情绪冲突与连续人物表演。",
    videoSrc: `${publicBase}videos/chosen-by-billionaire.mp4`,
    posterSrc: `${publicBase}covers/chosen-by-billionaire.jpg`,
    duration: "01:56",
    orientation: "竖屏",
  },
  {
    id: "desire",
    title: "欲望",
    category: "仿真人",
    summary: "仿真人悬疑题材样片，展示黑暗风格、道具细节与紧张叙事。",
    videoSrc: `${publicBase}videos/desire.mp4`,
    posterSrc: `${publicBase}covers/desire.jpg`,
    duration: "01:25",
    orientation: "竖屏",
  },
  {
    id: "wedding-betrayal",
    title: "婚礼上的背叛",
    category: "仿真人",
    summary: "仿真人海外情感短剧样片，展示婚礼冲突、人物对峙与情绪反转。",
    videoSrc: `${publicBase}videos/wedding-betrayal.mp4`,
    posterSrc: `${publicBase}covers/wedding-betrayal.jpg`,
    duration: "01:47",
    orientation: "竖屏",
  },
  {
    id: "corporate-spy",
    title: "商业间谍",
    category: "仿真人",
    summary: "仿真人商战短剧样片，展示职场对峙、身份悬念与竖屏叙事节奏。",
    videoSrc: `${publicBase}videos/corporate-spy.mp4`,
    posterSrc: `${publicBase}covers/corporate-spy.jpg`,
    duration: "01:40",
    orientation: "竖屏",
  },
  {
    id: "all-corrupted",
    title: "全员黑化",
    category: "仿真人",
    summary: "仿真人古装奇幻短剧样片，展示系统设定、情绪张力与连续人物表演。",
    videoSrc: `${publicBase}videos/all-corrupted.mp4`,
    posterSrc: `${publicBase}covers/all-corrupted.jpg`,
    duration: "01:10",
    orientation: "竖屏",
  },
  {
    id: "game-ad",
    title: "游戏广告",
    category: "游戏广告",
    summary: "三维游戏广告样片，展示角色塑造、剧情钩子与竖屏投放节奏。",
    videoSrc: `${publicBase}videos/game-ad.mp4`,
    posterSrc: `${publicBase}covers/game-ad.jpg`,
    duration: "00:30",
    orientation: "竖屏",
  },
];
