// 案例页唯一配置入口。
// 新增作品时，复制下面的对象模板到 caseVideos 数组中并填写内容即可。
// 视频和封面既可以使用云端地址，也可以放在 public/videos 与 public/covers 目录中。
//
// {
//   id: "唯一编号",
//   title: "作品标题",
//   category: "作品类型",
//   summary: "作品简介",
//   videoSrc: "视频地址",
//   posterSrc: "封面地址",
//   duration: "时长",
//   orientation: "横屏或竖屏",
// },

const publicBase = import.meta.env.BASE_URL;
const videoBase =
  "https://github.com/linwanxing666/huanhe-animation/releases/download/site-media-v1/";

const configuredCaseVideos = [
  {
    id: "soul-guide",
    title: "渡魂使者",
    category: "3D动漫",
    summary: "三维动漫叙事样片，呈现暗黑奇幻氛围与电影化镜头语言。",
    videoSrc: `${publicBase}videos/soul-guide.mp4`,
    posterSrc: `${publicBase}covers/soul-guide.jpg`,
    duration: "01:24",
    orientation: "横屏",
  },
  {
    id: "judge",
    title: "判官",
    category: "3D动漫",
    summary: "三维动漫奇幻短剧样片，展示现代与冥界交错、角色动作与电影化场景。",
    videoSrc: `${publicBase}videos/judge.mp4`,
    posterSrc: `${publicBase}covers/judge.jpg`,
    duration: "01:27",
    orientation: "横屏",
  },
  {
    id: "two-dimensional-anime",
    title: "二维动漫",
    category: "2D动漫",
    summary: "二维动漫叙事样片，展示风格化角色、生活化表演与连续画面。",
    videoSrc: `${publicBase}videos/2d-anime.mp4`,
    posterSrc: `${publicBase}covers/2d-anime.jpg`,
    duration: "01:16",
    orientation: "横屏",
  },
  {
    id: "redstone-village",
    title: "怒江红石村",
    category: "仿真人",
    summary: "仿真人现实题材样片，展示人物情绪、写实环境与竖屏叙事。",
    videoSrc: `${publicBase}videos/redstone-village.mp4`,
    posterSrc: `${publicBase}covers/redstone-village.jpg`,
    duration: "01:48",
    orientation: "竖屏",
  },
  {
    id: "ragnarok-trailer",
    title: "诸神黄昏预告",
    category: "仿真人",
    summary: "仿真人奇幻预告样片，展示神话世界、角色对峙与电影化视效。",
    videoSrc: `${publicBase}videos/ragnarok-trailer.mp4`,
    posterSrc: `${publicBase}covers/ragnarok-trailer.jpg`,
    duration: "01:01",
    orientation: "竖屏",
  },
  {
    id: "flash-marriage",
    title: "闪婚",
    category: "仿真人",
    summary: "仿真人都市情感样片，展示角色一致性、表演细节与短剧节奏。",
    videoSrc: `${publicBase}videos/flash-marriage.mp4`,
    posterSrc: `${publicBase}covers/flash-marriage.jpg`,
    duration: "01:03",
    orientation: "竖屏",
  },
  {
    id: "hospital-chaos",
    title: "医院闹翻天",
    category: "仿真人",
    summary: "仿真人喜剧短剧样片，展示医院群像、轻喜节奏与生活化表演。",
    videoSrc: `${publicBase}videos/hospital-chaos.mp4`,
    posterSrc: `${publicBase}covers/hospital-chaos.jpg`,
    duration: "01:16",
    orientation: "竖屏",
  },
  {
    id: "chosen-by-billionaire",
    title: "被当作小偷赶走，却被亿万富翁选中",
    category: "仿真人",
    summary: "仿真人海外短剧样片，展示身份反转、情绪冲突与连续人物表演。",
    videoSrc: `${publicBase}videos/chosen-by-billionaire.mp4`,
    posterSrc: `${publicBase}covers/chosen-by-billionaire.jpg`,
    duration: "01:56",
    orientation: "竖屏",
  },
  {
    id: "desire",
    title: "欲望",
    category: "仿真人",
    summary: "仿真人悬疑题材样片，展示黑暗风格、道具细节与紧张叙事。",
    videoSrc: `${publicBase}videos/desire.mp4`,
    posterSrc: `${publicBase}covers/desire.jpg`,
    duration: "01:25",
    orientation: "竖屏",
  },
  {
    id: "wedding-betrayal",
    title: "婚礼上的背叛",
    category: "仿真人",
    summary: "仿真人海外情感短剧样片，展示婚礼冲突、人物对峙与情绪反转。",
    videoSrc: `${publicBase}videos/wedding-betrayal.mp4`,
    posterSrc: `${publicBase}covers/wedding-betrayal.jpg`,
    duration: "01:47",
    orientation: "竖屏",
  },
  {
    id: "corporate-spy",
    title: "商业间谍",
    category: "仿真人",
    summary: "仿真人商战短剧样片，展示职场对峙、身份悬念与竖屏叙事节奏。",
    videoSrc: `${publicBase}videos/corporate-spy.mp4`,
    posterSrc: `${publicBase}covers/corporate-spy.jpg`,
    duration: "01:40",
    orientation: "竖屏",
  },
  {
    id: "all-corrupted",
    title: "全员黑化",
    category: "仿真人",
    summary: "仿真人古装奇幻短剧样片，展示系统设定、情绪张力与连续人物表演。",
    videoSrc: `${publicBase}videos/all-corrupted.mp4`,
    posterSrc: `${publicBase}covers/all-corrupted.jpg`,
    duration: "01:10",
    orientation: "竖屏",
  },
  {
    id: "save-wolf-commentary",
    title: "解说漫·拯救狼",
    category: "3D动漫",
    summary: "三维动物剧情解说样片，展示狼群叙事、森林氛围与长篇连续镜头。",
    videoSrc: `${publicBase}videos/save-wolf-commentary.mp4`,
    posterSrc: `${publicBase}covers/save-wolf-commentary.jpg`,
    duration: "04:36",
    orientation: "横屏",
  },
  {
    id: "farming-system",
    title: "种田系统",
    category: "3D动漫",
    summary: "三维动漫田园题材样片，展示群像角色、系统设定与轻喜剧情节奏。",
    videoSrc: `${publicBase}videos/farming-system.mp4`,
    posterSrc: `${publicBase}covers/farming-system.jpg`,
    duration: "02:24",
    orientation: "横屏",
  },
  {
    id: "aunt-baby-trailer",
    title: "人前阿姨人后宝宝预告",
    category: "3D动漫",
    summary: "三维动漫都市情感预告，展示细腻角色表演、夜景氛围与电影化构图。",
    videoSrc: `${publicBase}videos/aunt-baby-trailer.mp4`,
    posterSrc: `${publicBase}covers/aunt-baby-trailer.jpg`,
    duration: "01:04",
    orientation: "横屏",
  },
  {
    id: "aunt-baby",
    title: "人前阿姨人后宝宝",
    category: "3D动漫",
    summary: "三维动漫都市情感正片，呈现角色关系推进、微表情与连贯镜头调度。",
    videoSrc: `${publicBase}videos/aunt-baby.mp4`,
    posterSrc: `${publicBase}covers/aunt-baby.jpg`,
    duration: "01:02",
    orientation: "横屏",
  },
  {
    id: "lucky-child-shen-family",
    title: "小福宝进门，沈家要翻身",
    category: "仿真人",
    summary: "仿真人年代情感样片，展示家庭群像、年代场景与竖屏叙事节奏。",
    videoSrc: `${publicBase}videos/lucky-child-shen-family.mp4`,
    posterSrc: `${publicBase}covers/lucky-child-shen-family.jpg`,
    duration: "00:59",
    orientation: "竖屏",
  },
  {
    id: "family-reunion-banquet",
    title: "认亲宴上见真情",
    category: "仿真人",
    summary: "仿真人家庭情感样片，围绕认亲宴展开人物对峙与亲情反转。",
    videoSrc: `${publicBase}videos/family-reunion-banquet.mp4`,
    posterSrc: `${publicBase}covers/family-reunion-banquet.jpg`,
    duration: "01:50",
    orientation: "竖屏",
  },
  {
    id: "heiress-takes-control",
    title: "千金掌权，撕碎渣男美梦",
    category: "仿真人",
    summary: "仿真人海外情感样片，展示豪门博弈、身份反击与女性角色塑造。",
    videoSrc: `${publicBase}videos/heiress-takes-control.mp4`,
    posterSrc: `${publicBase}covers/heiress-takes-control.jpg`,
    duration: "01:21",
    orientation: "竖屏",
  },
  {
    id: "little-treasure",
    title: "萌宝",
    category: "仿真人",
    summary: "仿真人萌宝题材样片，展示儿童角色、家庭互动与温暖情绪表达。",
    videoSrc: `${publicBase}videos/little-treasure.mp4`,
    posterSrc: `${publicBase}covers/little-treasure.jpg`,
    duration: "01:00",
    orientation: "竖屏",
  },
  {
    id: "sweetheart",
    title: "甜心",
    category: "仿真人",
    summary: "仿真人海外职场情感样片，展示人物微表情、办公室场景与关系推进。",
    videoSrc: `${publicBase}videos/sweetheart.mp4`,
    posterSrc: `${publicBase}covers/sweetheart.jpg`,
    duration: "01:49",
    orientation: "竖屏",
  },
  {
    id: "ten-million-order",
    title: "签下千万大单，全组设局要我报销120万",
    category: "仿真人",
    summary: "仿真人职场逆袭样片，围绕千万订单展开团队设局与强势反击。",
    videoSrc: `${publicBase}videos/ten-million-order.mp4`,
    posterSrc: `${publicBase}covers/ten-million-order.jpg`,
    duration: "01:43",
    orientation: "竖屏",
  },
  {
    id: "wife-in-car",
    title: "车里的妻子",
    category: "仿真人",
    summary: "仿真人海外情感样片，以豪车与婚姻关系为线索推进悬念和人物冲突。",
    videoSrc: `${publicBase}videos/wife-in-car.mp4`,
    posterSrc: `${publicBase}covers/wife-in-car.jpg`,
    duration: "01:09",
    orientation: "竖屏",
  },
  {
    id: "triplets-marry-rich",
    title: "我靠三胞胎嫁豪门",
    category: "仿真人",
    summary: "仿真人海外家庭样片，展示三胞胎群像、豪门场景与轻喜情感冲突。",
    videoSrc: `${publicBase}videos/triplets-marry-rich.mp4`,
    posterSrc: `${publicBase}covers/triplets-marry-rich.jpg`,
    duration: "01:50",
    orientation: "竖屏",
  },
  {
    id: "black-gold-python",
    title: "乌金巨蟒",
    category: "仿真人",
    summary: "仿真人年代冒险样片，展示年代群像、乡村环境与悬疑事件铺陈。",
    videoSrc: `${publicBase}videos/black-gold-python.mp4`,
    posterSrc: `${publicBase}covers/black-gold-python.jpg`,
    duration: "01:20",
    orientation: "竖屏",
  },
  {
    id: "dragon-blood",
    title: "龙王之血",
    category: "仿真人",
    summary: "仿真人西方奇幻样片，展示王庭场景、史诗环境与人物命运冲突。",
    videoSrc: `${publicBase}videos/dragon-blood.mp4`,
    posterSrc: `${publicBase}covers/dragon-blood.jpg`,
    duration: "01:39",
    orientation: "竖屏",
  },
  {
    id: "touch-my-daughter",
    title: "谁敢动我的女儿",
    category: "仿真人",
    summary: "仿真人都市护女题材样片，展示高压对峙、亲情守护与动作场面。",
    videoSrc: `${publicBase}videos/touch-my-daughter.mp4`,
    posterSrc: `${publicBase}covers/touch-my-daughter.jpg`,
    duration: "01:43",
    orientation: "竖屏",
  },
  {
    id: "contract-husband",
    title: "抢我老婆？协议老公不装了",
    category: "仿真人",
    summary: "仿真人都市情感样片，展示雨夜冲突、身份反转与高张力人物对峙。",
    videoSrc: `${publicBase}videos/contract-husband.mp4`,
    posterSrc: `${publicBase}covers/contract-husband.jpg`,
    duration: "01:34",
    orientation: "竖屏",
  },
  {
    id: "mermaid",
    title: "美人鱼",
    category: "仿真人",
    summary: "仿真人西方奇幻样片，展示冰湖秘境、美人鱼角色与冒险情绪氛围。",
    videoSrc: `${publicBase}videos/mermaid.mp4`,
    posterSrc: `${publicBase}covers/mermaid.jpg`,
    duration: "01:17",
    orientation: "竖屏",
  },
  {
    id: "game-ad",
    title: "游戏广告",
    category: "游戏广告",
    summary: "三维游戏广告样片，展示角色塑造、剧情钩子与竖屏投放节奏。",
    videoSrc: `${publicBase}videos/game-ad.mp4`,
    posterSrc: `${publicBase}covers/game-ad.jpg`,
    duration: "00:30",
    orientation: "竖屏",
  },
];

export const caseVideos = configuredCaseVideos.map((item) => ({
  ...item,
  videoSrc: item.videoSrc.replace(`${publicBase}videos/`, videoBase),
}));
